### ISSUE TITLE
distribution 0.1.0 release: ATS target 1 tracking issue

### ISSUE THREAD

**Issue by trws** [flux-framework/distribution#1]
- [ ] Develop distribution source release process, with RFC; See #8
- [x] Default module list/initial program, either way a way to specify modules that should be loaded outside of source: See flux-framework/flux-core#508
- [ ] Sched integration: make having a scheduler for submit to use dependable
  - [ ] Sched installer of some description
  - [x] flux-core source package for out-of-tree build? See #5 and #4
  - [x] Sched autotools build (maybe)?  See flux-framework/flux-sched#83 
- [ ] integration tests for `flux submit` and general functionality

**Comment by springme** [comment]
Great, thank you!

**Comment by lipari** [comment]
In creating a current list of issues to address, I wanted to remind everyone of https://github.com/flux-framework/flux-plans/wiki/s4

In retrospect, this was not a very visible place to post and discuss our plans.  Perhaps it could be replaced someday.

**Comment by garlick** [comment]
I had the same thought.  Just opened #2 to suggest moving it here.

**Comment by garlick** [comment]
Per semantic versioning, first release is 0.1.0 and everything before 1.x is effectively alpha.
