### ISSUE TITLE
CTS-1 overall test plan

### ISSUE THREAD

**Issue by garlick** [flux-framework/distribution#12]
Plan for flux testing on [CTS-1](https://asc.llnl.gov/computers/cts1-rfp) during early access window. 

**_Target System**_

CTS-1 is a large system arriving at Livermore in early Summer 2016
- 12-scalable unit, 2304 node, 82.944 core
- Interconnect:  Intel OPA
- Operating system: TOSS 3 (RHEL 7.2 based) with slurm-2.3.3
- Single SU test system: opal.llnl.gov

**_Goals**_
- Fulfill obligation to test Flux on CTS-1 hardware
- Demonstrate Flux ability to run one broker per node, full-system
- Demonstrate Flux ability to run full-system MPI jobs, on all cores
- High throughput testing
- Testing with debugging tools
- Solid OS integration (slurm, MPI, TOSS3, etc)
- Improved integration with TCE-packaged tools and MPI

**_Plan**_

Specific tests areas with resource requirements and exit criteria
#13 CTS-1 launch Flux on full system
#14 CTS-1 flux-sched test plan

**_Entry issues**_

Issues that need to be solved in order for some tests to run
- [x] flux-framework/flux-core#630 support launching Intel MPI jobs on Intel OPA fabric
- [x] flux-framework/flux-sched#154 Questions that may arise in creating the first sched RPM package
- [x] flux-framework/flux-core#679 instrument flux-core startup/teardown phases
- [ ] flux-framework/flux-sched#166 Performance analysis for flux-sched

**_Exit issues**_

Issues discovered and/or fixed during testing.

**Comment by garlick** [comment]
```
Date: Wed, 25 May 2016 11:03:06 -0700
From: Jim Garlick
To: Greg Tomaschke, Scott Futral
Cc: Dave Fox, Trent D'Hooge, Becky Springmeyer
Subject: CTS-1 flux testing

Hi -

When CTS-1 enters the pre-GA application test phase, could the
Flux team have some test time?  We would run under SLURM like
a regular job, not replace it, so we could coexist with other
applications doing similar testing.

Our test plans are in the early stages and will depend on what sort
of access we can get and how you plan to run the machine during this
phase.  In our ideal world I think we'd like dedicated slot for a
couple hours a day over the course of a few weeks, ramping up slowly
from a couple of SU's to the full system.

Anyway would you please put us on the list of users wanting test time?

Thanks,

Jim
```

**Comment by grondo** [comment]
Thanks for opening this issue! Should we add, or does there exist some entry issues to do some basic scalability tests beforehand on order of 1-2K brokers?

I also assume before we run Slurm itself will have been show to be able to start a full system MPI job, hopefully using PMI?

What are the exit conditions for High Throughput Testing and Scale Testing (I guess that is what you want to nail down in this Issue?)

It would seem we could make progress on OS Integration and High Throughput testing before CTS-1 arraives.

**Comment by garlick** [comment]
Good questions.  Right I think they'll have SLURM working before handing the system over to apps.

What about opening an issue for each area of testing using a template in the description that includes an **exit criteria** section.  We can begin now on opal to push these forward and shake out issues that appear at 1-scalable unit.  We can link these into the **plan** section above.

**Comment by dongahn** [comment]
>  flux-framework/flux-sched#154 Questions that may arise in creating the first sched RPM package

I think it would be wise if we can get @tpatki's performance instrumentation into this to get a reasonable datapoint for the scheduler during this exercise. @tpatki, do you have an issue ticket for your work which we can tag here?

**Comment by dongahn** [comment]
Also, if we can get one hwloc xml export file from one of these CTS-1 systems, we can easily duplicate that into many to test scheduler scalability before running this on the actual CTS-1 system. Perhaps we can create another issue ticket to capture this as a pre-testing item.

**Comment by dongahn** [comment]
Thank you for adding Issue #14 up there!
