### ISSUE TITLE
distribution 0.2.0 release: ATS target 2 tracking issue

### ISSUE THREAD

**Issue by trws** [flux-framework/distribution#3]
- [ ] develop packaging strategy for key platforms
  - [ ] packaging guidelines/targets
  - [ ] dependent package/library management: #4 & #5
- [ ] ATS machine/scheduler module to interface with flux/capacitor
- [ ] Sched:
  - [ ] per-core scheduling
  - [ ] rank identification, actually use all nodes
- [ ] Handle scheduling by core without oversubscription
- [ ] Offer allocation of groups of cores to processes, or processes on individual cores
- [ ] Support up to thousands, think as high as 7-10 thousand, in an instance
- [ ] Scalability:
  - [ ] Job throughput
  - [ ] Memory
- [ ] Have distribution level tests
- [ ] Testing:
  - [ ] Node scalability baseline, uq-style?
  - [ ] Memory scalability baseline and analysis
  - [ ] Resilience baseline (kill some non-0 rank, kill rank 0)
  - [ ] sched performance
